name: Run unit tests
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install additional packages
        run: |
          set -ex
          apt -qy update
          apt -qy install lua5.1 liblua5.1-dev luarocks tidy build-essential
          luarocks install diff
          luarocks install luafilesystem
      - name: Install Lunamark
        run: luarocks make
      - name: Run unit tests
        run: make test
